version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    restart: always
volumes:
  mysql_data: